name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements/test.txt ]; then pip install -r requirements/test.txt; else pip install -r requirements.txt; fi
        
    - name: Check code style
      run: |
        flake8 .
        black --check .
        isort --check --profile black .
        
    - name: Run security checks
      run: |
        bandit -r task_manager tasks
        
    - name: Run tests
      run: |
        pytest --cov=. --cov-report=xml
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
        
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push web image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/production/Dockerfile.web
        push: true
        tags: |
          yourusername/taskmanager-web:latest
          yourusername/taskmanager-web:${{ github.sha }}
          
    - name: Build and push celery image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/production/Dockerfile.celery
        push: true
        tags: |
          yourusername/taskmanager-celery:latest
          yourusername/taskmanager-celery:${{ github.sha }}